# Generated by Django 5.2.8 on 2025-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('opisanie', models.CharField(max_length=100)),
            ],
        ),
    ]
